FROM python:3.10

RUN apt-get install wget
RUN pip install pandas sqlalchemy psycopg2

WORKDIR /app
COPY ingest_data_green_taxi.py ingest_data_green_taxi.py

ENTRYPOINT [ "python", "ingest_data_green_taxi.py"]
