version: "3.3"

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - type: bind
        source: /home/menoetius/de_zoomcamp/Week_1/ny_taxi_postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin

networks:
  pg-network:
    external: true

volumes:
  pgadmin_data: